version: '3'

services:

  stmm:
    image: stmm:v1
    networks:
      - web
    depends_on:
      - stmm_rt
    environment:
      STMM_HOST: "stmm_rt"
      STMM_PORT: "8077"
      DB_HOST: "localhost"
      DB_PORT: "8077"
      DB_NAME: "easytv"
      DB_USER: "easytv"
      DB_PASSWORD: "easytv"
    stdin_open: true
    tty: true
      
  stmm_rt:
    image: stmm_rt:v1
    networks:
      - web
    environment:
      PORT: "8077"

  rbmm:
    image: rbmm:v1
    networks:
      - web
    environment:
      PORT: "8080"

  hbmm:
    image: hbmm:v1
    networks:
      - web
    depends_on:
      - stmm_rt
      - rbmm
    environment:
      STMM_HOST: "stmm_rt"
      RBMM_HOST: "rbmm"
      STMM_PORT: "8077"
      RBMM_PORT: "8080"
      PORT: "8087 "
    ports:
      - "8087:8087"
      
networks:
  web:
