version: '3.1'

services:
    
  stmm:
    image: stmm:v1
    networks:
      - personalization-api_easytv_net
    depends_on:
      - stmm_rt
    environment:
      STMM_HOST: "stmm_rt"
      STMM_PORT: "8077"
      RBMM_HOST: "rbmm"
      RBMM_PORT: "8081"
      DB_HOST: "db"
      DB_PORT: "3306"
      DB_NAME: "easytv"
      DB_USER: "easytv"
      DB_PASSWORD: "easytv"
    stdin_open: true
    command: /opt/jdk/bin/java -Xms1024m -Xmx2048m -jar /root/STMM/EASYTV_STMM_profile_generator-0.0.1-SNAPSHOT-jar-with-dependencies.jar -e production
    tty: true

  stmm_rt:
    image: stmm_rt:v1
    networks:
      - personalization-api_easytv_net
    environment:
      PORT: "8077"
    ports:
      - "8077:8077"
  rbmm:
    image: rbmm:v1
    networks:
      - personalization-api_easytv_net
    environment:
      PORT: "8080"
    ports:
      - "8081:8081"

  hbmm:
    image: hbmm:v1
    networks:
      - personalization-api_easytv_net
    environment:
      STMM_HOST: "stmm_rt"
      RBMM_HOST: "rbmm"
      STMM_PORT: "8077"
      RBMM_PORT: "8081"
      DB_NAME: "easytv"
      DB_USER: "easytv"
      DB_PASS: "easytv"
      DB_HOST: "db"
      NODE_ENV: "production"
      JWT_SECRET: "./run/secret/jwt_secret"
      PORT: "8087 "
    ports:
      - "8087:8087"

networks:
  personalization-api_easytv_net:
    external: true