version: '3.1'

services:

  stmm:
    image: stmm:v1
    networks:
      - easytv_net
    depends_on:
      - stmm_rt
    environment:
      STMM_HOST: "stmm_rt"
      RBMM_HOST: "rbmm"
      STMM_PORT: "8077"
      RBMM_PORT: "8081"
      DB_HOST: "personalization_db"
      DB_PORT: "3306"
      DB_NAME: "easytv"
      DB_USER: "easytv"
      DB_PASSWORD_FILE: "/run/secrets/hpapidb_pass"
    stdin_open: true
    tty: true
    secrets:
      - hpapidb_pass
      - hpapidbroot_password
      
  stmm_rt:
    image: stmm_rt:v1
    networks:
      - easytv_net
    environment:
      PORT: "8077"

  rbmm:
    image: rbmm:v1
    networks:
      - easytv_net
    environment:
      PORT: "8081"

  hbmm:
    image: hbmm:v1
    networks:
      - easytv_net
    depends_on:
      - personalization_db
      - stmm_rt
      - rbmm
    environment:
      STMM_HOST: "stmm_rt"
      RBMM_HOST: "rbmm"
      STMM_PORT: "8077"
      RBMM_PORT: "8081"
      DB_HOST: "personalization_db"
      DB_PORT: "3306"
      DB_NAME: "easytv"
      DB_USER: "easytv"
      NODE_ENV: "production"
      DB_PASSWORD_FILE: "/run/secrets/hpapidb_pass"
      JWT_SECRET: "/run/secrets/jwt_secret"
      PORT: "8087"
      http_proxy: "http://161.27.206.250:8080"
      https_proxy: "http://161.27.206.250:8080"
      no_proxy: ".easytv.eng.it, rbmm, stmm_rt" 
    secrets:
      - hpapidb_pass
      - hpapidbroot_password
      - jwt_secret
    ports:
      - "8087:8087"

secrets:
  hpapidb_pass:
    external: true
  hpapidbroot_password:
    external: true
  jwt_secret:
    external: true

networks:
  easytv_net:
    external: true